name: SecDim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  secdim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a1b6c2131848c4e76e7cd203b385fdc7b7c66e90
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@8a2c65df0f74198ef4f15c12be7dbe38551b20e7
        with:
          python-version: '3.11'

      - name: Clean pip config and env
        run: |
          rm -rf $HOME/.config/pip $HOME/.pip || true
        shell: bash

      - name: Install dependencies (secure)
        run: pip install --no-index -r requirements.txt
        env:
          PIP_INDEX_URL: ""
          PIP_EXTRA_INDEX_URL: ""
